### ISSUE TITLE
How to configure on Desktop ?

### ISSUE THREAD

**Issue by ghost** [segura2010/GoHole-CryptClient#1]
Users ( like me ) need to configure their OS to use the local proxy right ?

Any chance you can add this ?
maybe just some links to start the ball rolling ?

**Comment by segura2010** [comment]
Yes, you always need to configure your OS to use the DNS server you want (for example your GoHole server).

This client is only to connect to the DNS server using the encrypted protocol instead of using the clear text protocol, so anyone between you and the server cannot see what domains you are requesting (and visiting).

I am not going to include any way to "auto configure" the DNS server in your OS, it is not difficult.. It is more difficult to set up the GoHole server than configuring the OS to use it.
